### PR TITLE
VCR cassettes refresh

### PR DESCRIPTION
**Pull request by tjchambers**
Clear out old specs from block_score directory and below and regenerate them in the new proper location.

This is based on top of PR #83

### CODE REVIEW

**Comment by tjchambers** [comment]
@dkubb - this is a cleanup of the current VCR cassettes. It is based on #83

**Comment by dkubb** [comment]
@tjchambers I added another commit that cleans up all the remaining vcr cassettes.

Since it's just a removal I'll merge the PR once all the specs are green.

**Comment by mbj** [comment]
@dkubb What about adding a check on CI there are no stale VCR cassettes? This would force not to introduce such "dead fixture data regressions".

**Comment by tjchambers** [comment]
@mbj I didn't know that could be done.

**Pull request merged**
