### PR TITLE
Enhance deletes specifications

### PR DESCRIPTION
**Pull request by tjchambers**
Add more tests to confirm deeper behavior on delete actions, This includes testing for prior deletions.

### CODE REVIEW

**Comment by tjchambers** [comment]
@dkubb for your review

**Comment by tjchambers** [comment]
@dkubb I tested rebasing on master (didn't expect it to work), and I was right so I will leave this one on top of PR #74.

**Comment by dkubb** [comment]
@tjchambers mutant found some commits in this PR where code was changed without being fully covered by specs.

**Comment by dkubb** [comment]
@tjchambers It looks like the specs in one of the commits still fails. I assume you have to do a bit more to turn off vcr when mutant is running to make this spec pass.

**Comment by tjchambers** [comment]
@dkubb this is ready for another pass

**Pull request merged**
