### PR TITLE
Correct test descriptions

### PR DESCRIPTION
**Pull request by tjchambers**

### CODE REVIEW

**Comment by tjchambers** [comment]
Appears I need to learn more about VCR.

**Comment by backus** [comment]
This looks good so far @tjchambers. If you find the mapping of test descriptions to filenames awkward you can always change that. This lives here: https://github.com/BlockScore/blockscore-ruby/blob/master/spec/vcr_setup.rb#L42-L52

**Comment by tjchambers** [comment]
@dkubb please comment on this PR when time permits. Thanks.

**Comment by dkubb** [comment]
@tjchambers @backus what's your feelings on git commit history rewriting? I typically would rewrite a *branch's* history so that each commit is a single logical change, and passes the CI. I find it useful for debugging things with `git bisect`. The process takes a bit getting used to, which is why I bring it up for discussion.

**Comment by dkubb** [comment]
@tjchambers other than my comment above I have no further flags to add.

**Comment by tjchambers** [comment]
@dkubb Yes - I was not aware of the intimacy vcr has with the names of the tests. I need to get use to the rearranging of a number of files each time I modify a test name. I believe @backus was ok with writing this change off to a learning experience. 

Perhaps there is a more expedient way for me to use vcr.

**Comment by backus** [comment]
@dkubb Check out our hipchat. I touched on this earlier and linked one of our internal guides

**Pull request merged**
